'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ajuda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajuda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property apple223() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apple223", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property avancar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("avancar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beat1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beat1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botao_apagar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botao_apagar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botao_encerrar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botao_encerrar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botao_fechar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botao_fechar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botao_iniciar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botao_iniciar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botao_iniciar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botao_iniciar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botao_media() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botao_media", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property botao_salvar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botao_salvar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cabana_quadrado0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cabana_quadrado0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cabana_quadrado1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cabana_quadrado1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cabana_quadrado2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cabana_quadrado2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cabana_quadrado3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cabana_quadrado3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cabana_quadrado31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cabana_quadrado31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cabana_quadrado4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cabana_quadrado4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cabana_quadrado5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cabana_quadrado5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cabana_quadrado6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cabana_quadrado6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property farmer_cabana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer_cabana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property farmer_floresta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer_floresta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property farmer_galinheiro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer_galinheiro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property farmer_plantacao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer_plantacao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property farmer_pomar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer_pomar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property farmer_resposta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer_resposta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property farmer_tela_inicial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("farmer_tela_inicial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fases_cabana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fases_cabana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fases_floresta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fases_floresta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fases_galinheiro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fases_galinheiro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fases_plantacao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fases_plantacao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fases_pomar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fases_pomar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fases_riacho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fases_riacho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fazenda_modelo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fazenda_modelo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fish1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fish1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fish2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fish2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fish3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fish3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fish4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fish4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property floresta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("floresta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property floresta_quadrado1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("floresta_quadrado1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property floresta_quadrado2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("floresta_quadrado2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property floresta_quadrado3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("floresta_quadrado3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property floresta_quadrado4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("floresta_quadrado4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property floresta_quadrado5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("floresta_quadrado5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fundo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fundopomar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundopomar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property galinha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("galinha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property galinhaovos1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("galinhaovos1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property galinheiro_quadrado0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("galinheiro_quadrado0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property galinheiro_quadrado01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("galinheiro_quadrado01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property galinheiro_quadrado1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("galinheiro_quadrado1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property galinheiro_quadrado2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("galinheiro_quadrado2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property galinheiro_quadrado3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("galinheiro_quadrado3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property galinheiro_quadrado4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("galinheiro_quadrado4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property galinheiro_quadrado5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("galinheiro_quadrado5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property galinheiro_quadrado6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("galinheiro_quadrado6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imagem_cenoura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imagem_cenoura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imagens1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imagens1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imageteste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageteste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgminh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgminh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property luvas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("luvas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mensagem_ajuda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mensagem_ajuda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mensagem_cabana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mensagem_cabana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mensagem_floresta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mensagem_floresta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mensagem_galinheiro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mensagem_galinheiro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mensagem_insira() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mensagem_insira", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mensagem_plantacao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mensagem_plantacao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mensagem_pomar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mensagem_pomar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mensagem_riacho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mensagem_riacho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property owl1_verde() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("owl1_verde", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property owl3_oliva() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("owl3_oliva", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property owl4_laranja() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("owl4_laranja", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property owl5_lilas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("owl5_lilas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property owl6_azulescuro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("owl6_azulescuro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plantacao_quadrado01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plantacao_quadrado01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plantacao_quadrado1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plantacao_quadrado1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plantacao_quadrado2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plantacao_quadrado2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plantacao_quadrado3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plantacao_quadrado3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plantacao_quadrado4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plantacao_quadrado4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plantacao_quadrado5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plantacao_quadrado5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plantacao_quadrado6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plantacao_quadrado6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plantacao_quadrado7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plantacao_quadrado7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plantacao_quadrado8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plantacao_quadrado8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plantacao_quadrado9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plantacao_quadrado9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pomar_quadrado0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pomar_quadrado0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pomar_quadrado01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pomar_quadrado01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pomar_quadrado1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pomar_quadrado1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pomar_quadrado10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pomar_quadrado10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pomar_quadrado11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pomar_quadrado11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pomar_quadrado12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pomar_quadrado12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pomar_quadrado2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pomar_quadrado2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pomar_quadrado3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pomar_quadrado3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pomar_quadrado4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pomar_quadrado4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pomar_quadrado5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pomar_quadrado5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pomar_quadrado6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pomar_quadrado6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pomar_quadrado7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pomar_quadrado7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pomar_quadrado8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pomar_quadrado8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pomar_quadrado9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pomar_quadrado9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quadrado1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quadrado1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quadrado2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quadrado2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quadrado3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quadrado3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quadrado4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quadrado4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quadrado5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quadrado5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quadrado6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quadrado6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quadrado7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quadrado7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quadrado8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quadrado8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quadrado9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quadrado9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property regador() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("regador", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property seuari() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seuari", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tesourao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tesourao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property valley() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("valley", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property valley_shed1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("valley_shed1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property valley_shed11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("valley_shed11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property valley1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("valley1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property valley11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("valley11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property valley12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("valley12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property valleygalinheiro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("valleygalinheiro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property valleygalinheiro1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("valleygalinheiro1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property voltar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("voltar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
